### ISSUE TITLE
Syndication to Twitter fails silently when resulting tweet is >140 chars

### ISSUE THREAD

**Issue by gordon-morehouse** [hannesmannerheim/qvitter#136]
When using a 140-char-limited Quitter instance such as quitter.se, composing a queet of about 140 chars can result in an equivalent tweet that is >140 chars. This may have to do with URL shortening and/or hashtagging.

WHAT ACTUALLY HAPPENS:

If the user's account is set up to publish all Quitter queets to Twitter, the process will fail with no error message in the above case.

WHAT I EXPECT TO HAPPEN:

If publishing to Twitter fails for any reason, the user should be notified, preferably with option to resend or edit & resend.

**Comment by hannesmannerheim** [comment]
i suspect this is due to twitter actually make some url:s longer with their t.co "shortener". if you post a really short url, the resulting t.co-url can becomes longer... 

anyway i think you are right, the user should be notified. but 1) that needs to be solved at a gnusocial level, in the twitterbridge plugin and 2) i suspect it's not straightforward since i think this is handled by queuedaemon, so theoretically it can fail delivering to twitter say two minutes after posting the notice... this can of course be solved but not super easy.

i'm closing this since i think it should be addressed in the gnu social bug-tracker https://bugz.foocorp.net/

**Comment by gordon-morehouse** [comment]
I'll repost on their tracker. I appreciate your (and their) patience with me occasionally misfiling bugs as I can't tell where Qvitter ends and GNUsocial begins. :)

**Comment by gordon-morehouse** [comment]
https://bugz.foocorp.net/T90
