### ISSUE TITLE
@username@twitter.com could link to someone's Twitter profile

### ISSUE THREAD

**Issue by Lottiotta** [hannesmannerheim/qvitter#153]
It works with other instances of GNU Social stuff, as it does that profile-pop-up thing and presumably sends a notification.

For @username@twitter.com I understand that it probably couldn't do the profile-pop-up thing or the notification thing, but it could maybe open someone's profile in a new tab? I think it would be better than it doing nothing at all, anyway. I could just post a link to their Twitter account but that seems inconsistent!

(I know, this may well not be worth the work. But I like the idea so I thought I'd share it.)

**Comment by hannesmannerheim** [comment]
it's more of an gnu social feature request than one for qvitter. but i don't think i agree, since twitter doesn't support ostatus, i don't think we should mix twitter stuff with ostatus syntax. making @username@twitter.com links get linkified might fool people into believing the twitter users will receive a notification on twitter.

**Comment by Lottiotta** [comment]
That is a very good point. :)
