### ISSUE TITLE
Sign-up broken for Quitter.se

### ISSUE THREAD

**Issue by Cassolotl** [hannesmannerheim/qvitter#156]
(I don't know how to report this bug. I tried emailing En Kompis Kompis but I got no acknowledgement and the bug is still there.)

When signing up on Firefox and Chrome (I was on a Mac), new users signing up get stuck on this loading screen forever:

![screen shot 2015-04-05 at 11 35 28](https://cloud.githubusercontent.com/assets/6607512/6996620/f3a84004-db8a-11e4-8fa2-e1be90836946.png)

In the end I managed to join using my friend's laptop, which runs Debian, and the browser was Iceweasel.

**Comment by Lottiotta** [comment]
Here are three accurate screenshots of the issue:

Chrome Version 41.0.2272.118 (64-bit), Mac OS X 10.10.2:

![chrome screen shot 2015-04-05 at 12 42 37](https://cloud.githubusercontent.com/assets/6607512/6996754/5cbe32e4-db93-11e4-8700-af9a54288b4a.png)

Firefox 36.0.1, same Mac OS X 10.10.2:

![firefox screen shot 2015-04-05 at 12 45 08](https://cloud.githubusercontent.com/assets/6607512/6996755/69e37510-db93-11e4-9b2c-bb94dc27841b.png)

Safari Version 8.0.4 (10600.4.10.7), same Mac OS X 10.10.2:

![safari screen shot 2015-04-05 at 12 50 46](https://cloud.githubusercontent.com/assets/6607512/6996758/7a796ace-db93-11e4-88f9-36e173535484.png)

@darksider3@quitter.se said (and I didn't understand):

And BTW: StartSSL has actually a problem with theyr Authenticationservers, and Firefox has problems to auth the cert without them So that's can be a reason, because quitter.se fully operates over SSL. Chrome have no problems with that. Yeah, like i said: The StartSSL Servers *have problems actually*. Please wait a while, to give them time to get them the servers back working. I really don't know. I've tried in Chromium on Debian Jessie - javascript says error. Because he cannot connect to the HTTPS Version. That references again back to the StartSSL-Server problems. So you can report that bug, when the SSL-Problems are solved by the StartSSL-Servers. I see, you have already written a bug report at the right place(qvitter at Github). So please, wait, that we get a responce from any verified source(Admin i.e.)

Quitter.se is not very accessible to people who don't code (like me). I was told by another user that I was imagining this bug, even after explaining that I know of two other people experiencing this issue.

**Comment by tuupola** [comment]
I was trying to register yesterday for quitter.se. Got stuck on loading screen forever: Looked at JavaScript console and `/api/register.json` (or something similar, do not remember anymore) was returning 404. Tried quitter.no and it worked right away.

**Comment by moshpirit** [comment]
I think that's a quitter.se issue, instead of a Qvitter one since it doesn't depend of the interface, just the server, but I can be wrong.

**Comment by hannesmannerheim** [comment]
moshpirit is right, this is most likely quitter.se having a time limit on registrations. if you register "too fast", you are assumed to be a bot. we should change that time limit to something smaller, so humans don't get caught, and add better error reporting in qvitter.

**Comment by moshpirit** [comment]
Maybe showing a chronometer could be a good idea to let us know how much time do we have. Something like this: 

![chronometer](https://cloud.githubusercontent.com/assets/7888062/7032995/109bf974-dd77-11e4-8daf-715a51642e44.png)

(The [Oxygen](https://commons.wikimedia.org/wiki/File:Oxygen480-actions-chronometer.svg) icon has been partially used)

**Comment by sergeevabc** [comment]
Sign up is still broken, alas.

**Comment by hannesmannerheim** [comment]
i think this is resolved now. just open it again if you hear someone have the problem still

**Comment by rilut** [comment]
Still broken for me
