### ISSUE TITLE
Make qvitter compatible with GNU LibreJS

### ISSUE THREAD

**Issue by pizzamaker** [hannesmannerheim/qvitter#308]
As of now, LibreJS has trouble recognizing qvitter's JS licence(s). Here's a guide on how to iron out this bug: https://www.fsf.org/blogs/licensing/rel-jslicense

Also: https://www.gnu.org/philosophy/javascript-trap.html#AppendixA

**Comment by hannesmannerheim** [comment]
i've put hours into making librejs work with qvitter before, and i have succeeded but then it stops working again. librejs just too buggy! i hate it! 

problem is that librejs parses the js files and there is some fuckup in the code that makes librejs throw a "syntax error" on certain unicode chars, or something like that. and it's impossible to find which char is the problem. 

just uninstall librejs and the issue is solved.
