### ISSUE TITLE
What just happened here?

### ISSUE THREAD

**Issue by abjectio** [hannesmannerheim/qvitter#316]
Don't know if this is qvitter or not - I've pinged @mmn also on irc.

This notice : https://quitter.no/notice/801257 
became 
this :  https://anarchy.social/notice/12781

Strange. Both instances running latest master from GNU social and qvitter

**Comment by mmn** [comment]
On 2015-11-23 16:37, Knut Erik Hollund wrote:
> Don't know if this is qvitter or not - I've pinged @mmn
> <https://github.com/mmn> also on irc.
> 
> This notice : https://quitter.no/notice/801257
> became
> this : https://anarchy.social/notice/12781

Haha! Yeah. I would guess that it occurred since the salmon-based group
distribution from quitter.se was faster than the PuSH feed distribution
from your original node.

-- 
Mikael Nordfeldth
https://blog.mmn-o.se/
XMPP/mail: mmn@hethane.se
OpenPGP Fingerprint: AE68 9813 0B7C FCE3 B2FA 727B C7CE 635B B52E

**Comment by abjectio** [comment]
:-) - ok. make sense since the qvitter group is on quitter.se - arghh so an instance with restrictions on characters could kill the redistribution of queets (only if you are mention a group though... or?)

**Comment by hannesmannerheim** [comment]
wouldn't it be easy to just add a feature to replace the content of a notice when the push feed from the original instance arrives? a simple if-statement and update the row in the db?

**Comment by hannesmannerheim** [comment]
but closing this since it's not a qvitter issue
